name: Android Build CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Locate gradlew file
        run: |
          chmod +x $(find . -name gradlew)

      - name: Build with Gradle
        run: |
          ./$(find . -name gradlew) build
          
